### ISSUE TITLE
You mention "president" but don't explain in readme

### ISSUE THREAD

**Issue by keppel2** [theworldbright/Daifugo#3]

**Comment by keppel2** [comment]
@KentShikama yo, I'm taking an interest in your repo!

**Comment by KentShikama** [comment]
See https://en.wikipedia.org/wiki/Daifug%C5%8D or https://en.wikipedia.org/wiki/President_%28card_game%29 if you want more information on the origins of the game. Feel free to ask questions about this repo or fork/use it but I have no intention of maintaining this or updating anything. The default server that I used to host it with is no longer up.
